### ISSUE TITLE
java.lang.NullPointerException: Ticking block entity MobToGeneRegistry.java:139

### ISSUE THREAD

**Issue by 7eggert** [TheUnderTaker11/GeneticsReborn#149]
```
Time: 3/13/20 5:05 PM
Description: Ticking block entity

java.lang.NullPointerException: Ticking block entity
	at com.theundertaker11.geneticsreborn.api.capability.genes.MobToGeneRegistry.getGene(MobToGeneRegistry.java:139)
	at com.theundertaker11.geneticsreborn.blocks.dnadecrypter.GRTileEntityDNADecrypter.getSmeltingResultForItem(GRTileEntityDNADecrypter.java:54)
	at com.theundertaker11.geneticsreborn.blocks.dnadecrypter.GRTileEntityDNADecrypter.smeltItem(GRTileEntityDNADecrypter.java:85)
	at com.theundertaker11.geneticsreborn.blocks.dnadecrypter.GRTileEntityDNADecrypter.smeltItem(GRTileEntityDNADecrypter.java:69)
	at com.theundertaker11.geneticsreborn.blocks.dnadecrypter.GRTileEntityDNADecrypter.func_73660_a(GRTileEntityDNADecrypter.java:37)
	at net.minecraft.world.World.func_72939_s(World.java:1838)
	at net.minecraft.client.Minecraft.func_71407_l(Minecraft.java:1847)
	at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:1098)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:398)
	at net.minecraft.client.main.Main.main(SourceFile:123)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Client thread
Stacktrace:
	at com.theundertaker11.geneticsreborn.api.capability.genes.MobToGeneRegistry.getGene(MobToGeneRegistry.java:139)
	at com.theundertaker11.geneticsreborn.blocks.dnadecrypter.GRTileEntityDNADecrypter.getSmeltingResultForItem(GRTileEntityDNADecrypter.java:54)
	at com.theundertaker11.geneticsreborn.blocks.dnadecrypter.GRTileEntityDNADecrypter.smeltItem(GRTileEntityDNADecrypter.java:85)
	at com.theundertaker11.geneticsreborn.blocks.dnadecrypter.GRTileEntityDNADecrypter.smeltItem(GRTileEntityDNADecrypter.java:69)
	at com.theundertaker11.geneticsreborn.blocks.dnadecrypter.GRTileEntityDNADecrypter.func_73660_a(GRTileEntityDNADecrypter.java:37)

-- Block entity being ticked --
Details:
	Name: minecraft:grtileentitydnadecrypter // com.theundertaker11.geneticsreborn.blocks.dnadecrypter.GRTileEntityDNADecrypter
	Block type: ID #1119 (tile.dnadecrypter // com.theundertaker11.geneticsreborn.blocks.dnadecrypter.DNADecrypter // geneticsreborn:dnadecrypter)
	Block data value: 3 / 0x3 / 0b0011
	Block location: World: (181,63,249), Chunk: (at 5,3,9 in 11,15; contains blocks 176,0,240 to 191,255,255), Region: (0,0; contains chunks 0,0 to 31,31, blocks 0,0,0 to 511,255,511)
	Actual block type: ID #1119 (tile.dnadecrypter // com.theundertaker11.geneticsreborn.blocks.dnadecrypter.DNADecrypter // geneticsreborn:dnadecrypter)
	Actual block data value: 3 / 0x3 / 0b0011
Stacktrace:
	at net.minecraft.world.World.func_72939_s(World.java:1838)

-- Affected level --
Details:
	Level name: MpServer
	All players: 1 total; [GCEntityClientPlayerMP['7eggert'/419, l='MpServer', x=181.10, y=60.56, z=252.13]]
	Chunk stats: MultiplayerChunkCache: 14, 14
	Level seed: 0
	Level generator: ID 00 - default, ver 1. Features enabled: false
	Level generator options: 
	Level spawn location: World: (192,64,236), Chunk: (at 0,4,12 in 12,14; contains blocks 192,0,224 to 207,255,239), Region: (0,0; contains chunks 0,0 to 31,31, blocks 0,0,0 to 511,255,511)
	Level time: 9089167 game time, 4232098 day time
	Level dimension: 0
	Level storage version: 0x00000 - Unknown?
	Level weather: Rain time: 0 (now: false), thunder time: 0 (now: false)
	Level game mode: Game mode: survival (ID 0). Hardcore: false. Cheats: false
	Forced entities: 36 total; [EntityBat['Bat'/129, l='MpServer', x=171.75, y=39.10, z=237.44], EntityVillager['Villager'/130, l='MpServer', x=161.30, y=63.00, z=254.30], EntityVillager['Villager'/131, l='MpServer', x=163.30, y=63.00, z=254.30], EntityBlaze['Blaze'/132, l='MpServer', x=161.37, y=76.00, z=241.58], EntityBlaze['Blaze'/133, l='MpServer', x=162.31, y=74.51, z=242.31], EntityBlaze['Blaze'/134, l='MpServer', x=164.25, y=83.00, z=244.00], EntityBlaze['Blaze'/135, l='MpServer', x=162.42, y=82.00, z=243.93], EntityCyberZombie['Cyberzombie'/136, l='MpServer', x=176.09, y=49.00, z=263.59], EntityCreeper['Creeper'/93, l='MpServer', x=132.50, y=54.00, z=253.50], GCEntityClientPlayerMP['7eggert'/419, l='MpServer', x=181.10, y=60.56, z=252.13], EntityCreeper['Creeper'/167, l='MpServer', x=187.09, y=15.00, z=252.48], EntityChicken['Chicken'/168, l='MpServer', x=185.80, y=41.00, z=245.09], EntityChicken['Chicken'/169, l='MpServer', x=183.70, y=41.00, z=244.20], EntityChicken['Chicken'/170, l='MpServer', x=184.57, y=41.00, z=244.20], EntityChicken['Chicken'/171, l='MpServer', x=185.80, y=41.00, z=244.20], EntityChicken['Chicken'/172, l='MpServer', x=185.80, y=41.00, z=246.26], EntityChicken['Chicken'/173, l='MpServer', x=185.26, y=41.00, z=246.80], EntityChicken['Chicken'/174, l='MpServer', x=183.20, y=41.00, z=244.20], EntityVillager['Villager'/111, l='MpServer', x=157.30, y=63.00, z=254.30], EntityChicken['Chicken'/175, l='MpServer', x=184.59, y=40.63, z=246.57], EntityVillager['Villager'/112, l='MpServer', x=153.70, y=63.00, z=254.30], EntityChicken['Chicken'/176, l='MpServer', x=183.20, y=41.00, z=244.70], EntityVillager['Villager'/113, l='MpServer', x=151.70, y=63.00, z=254.30], EntityChicken['Chicken'/177, l='MpServer', x=184.94, y=41.75, z=244.20], EntityVillager['Villager'/114, l='MpServer', x=155.70, y=63.00, z=254.30], EntityChicken['Chicken'/178, l='MpServer', x=185.80, y=41.00, z=244.64], EntityVillager['Villager'/115, l='MpServer', x=159.30, y=63.00, z=254.30], EntityChicken['Chicken'/179, l='MpServer', x=183.20, y=41.00, z=244.20], EntityChicken['Chicken'/180, l='MpServer', x=185.80, y=41.00, z=246.80], EntityChicken['Chicken'/181, l='MpServer', x=184.10, y=41.00, z=244.20], EntityChicken['Chicken'/182, l='MpServer', x=185.33, y=41.00, z=244.20], EntityChicken['Chicken'/183, l='MpServer', x=183.20, y=41.00, z=245.11], EntityCow['Cow'/184, l='MpServer', x=188.71, y=58.00, z=240.31], EntityCow['Cow'/185, l='MpServer', x=187.45, y=58.00, z=242.00], EntityCow['Cow'/186, l='MpServer', x=187.45, y=58.00, z=240.91], EntityBat['Bat'/187, l='MpServer', x=184.36, y=22.00, z=277.53]]
	Retry entities: 0 total; []
	Server brand: fml,forge
	Server type: Integrated singleplayer server
Stacktrace:
	at net.minecraft.client.multiplayer.WorldClient.func_72914_a(WorldClient.java:420)
	at net.minecraft.client.Minecraft.func_71396_d(Minecraft.java:2741)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:419)
	at net.minecraft.client.main.Main.main(SourceFile:123)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

-- System Details --
Details:
	Minecraft Version: 1.12.2
	Operating System: Linux (amd64) version 5.5.5-1-default
	Java Version: 1.8.0_242, IcedTea
	Java VM Version: OpenJDK 64-Bit Server VM (mixed mode), IcedTea
	Memory: 2660346144 bytes (2537 MB) / 4261412864 bytes (4064 MB) up to 8589934592 bytes (8192 MB)
	JVM Flags: 7 total; -Xmx8G -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=32M
	IntCache: cache: 0, tcache: 0, allocated: 12, tallocated: 94
	FML: MCP 9.42 Powered by Forge 14.23.5.2847 56 mods loaded, 56 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored

	| State  | ID                                | Version                      | Source                                                         | Signature                                |
	|:------ |:--------------------------------- |:---------------------------- |:-------------------------------------------------------------- |:---------------------------------------- |
	| LCHIJA | minecraft                         | 1.12.2                       | minecraft.jar                                                  | None                                     |
	| LCHIJA | mcp                               | 9.42                         | minecraft.jar                                                  | None                                     |
	| LCHIJA | FML                               | 8.0.99.99                    | forge-1.12.2-14.23.5.2847.jar                                  | None                                     |
	| LCHIJA | forge                             | 14.23.5.2847                 | forge-1.12.2-14.23.5.2847.jar                                  | None                                     |
	| LCHIJA | micdoodlecore                     |                              | minecraft.jar                                                  | None                                     |
	| LCHIJA | xaerominimap_core                 | 1.12.2-1.0                   | minecraft.jar                                                  | None                                     |
	| LCHIJA | opencomputers|core                | 1.7.5.192                    | minecraft.jar                                                  | None                                     |
	| LCHIJA | basemetals                        | 2.5.0-beta6                  | BaseMetals-1.12.2.jar                                          | d476d1b22b218a10d845928d1665d45fce301b27 |
	| LCHIJA | bdlib                             | 1.14.3.12                    | bdlib-1.14.3.12-mc1.12.2.jar                                   | None                                     |
	| LCHIJA | codechickenlib                    | 3.2.3.358                    | CodeChickenLib-1.12.2-3.2.3.358-universal.jar                  | f1850c39b2516232a2108a7bd84d1cb5df93b261 |
	| LCHIJA | chickenchunks                     | 2.4.2.74                     | ChickenChunks-1.12.2-2.4.2.74-universal.jar                    | f1850c39b2516232a2108a7bd84d1cb5df93b261 |
	| LCHIJA | redstoneflux                      | 2.1.0                        | RedstoneFlux-1.12-2.1.0.6-universal.jar                        | 8a6abf2cb9e141b866580d369ba6548732eff25f |
	| LCHIJA | cofhcore                          | 4.6.3                        | CoFHCore-1.12.2-4.6.3.27-universal.jar                         | None                                     |
	| LCHIJA | cofhworld                         | 1.3.1                        | CoFHWorld-1.12.2-1.3.1.7-universal.jar                         | 8a6abf2cb9e141b866580d369ba6548732eff25f |
	| LCHIJA | cyclopscore                       | 1.6.1                        | CyclopsCore-1.12.2-1.6.1.jar                                   | bd0353b3e8a2810d60dd584e256e364bc3bedd44 |
	| LCHIJA | colossalchests                    | 1.7.3                        | ColossalChests-1.12.2-1.7.3-285.jar                            | bd0353b3e8a2810d60dd584e256e364bc3bedd44 |
	| LCHIJA | cyberware                         | 0.2.11.22                    | cyberware-1.12.2-0.2.11.22.jar                                 | None                                     |
	| LCHIJA | endercore                         | 1.12.2-0.5.73                | EnderCore-1.12.2-0.5.73.jar                                    | None                                     |
	| LCHIJA | jei                               | 4.15.0.293                   | jei_1.12.2-4.15.0.293.jar                                      | None                                     |
	| LCHIJA | thermalfoundation                 | 2.6.3                        | ThermalFoundation-1.12.2-2.6.3.27-universal.jar                | 8a6abf2cb9e141b866580d369ba6548732eff25f |
	| LCHIJA | thermalexpansion                  | 5.5.4                        | ThermalExpansion-1.12.2-5.5.4.43-universal.jar                 | 8a6abf2cb9e141b866580d369ba6548732eff25f |
	| LCHIJA | enderio                           | 5.1.55                       | EnderIO-1.12.2-5.1.55.jar                                      | None                                     |
	| LCHIJA | enderiointegrationtic             | 5.1.55                       | EnderIO-1.12.2-5.1.55.jar                                      | None                                     |
	| LCHIJA | enderiobase                       | 5.1.55                       | EnderIO-1.12.2-5.1.55.jar                                      | None                                     |
	| LCHIJA | enderioconduits                   | 5.1.55                       | EnderIO-1.12.2-5.1.55.jar                                      | None                                     |
	| LCHIJA | enderioconduitsappliedenergistics | 5.1.55                       | EnderIO-1.12.2-5.1.55.jar                                      | None                                     |
	| LCHIJA | opencomputers                     | 1.7.5.192                    | OpenComputers-MC1.12.2-1.7.5.192.jar                           | None                                     |
	| LCHIJA | enderioconduitsopencomputers      | 5.1.55                       | EnderIO-1.12.2-5.1.55.jar                                      | None                                     |
	| LCHIJA | enderioconduitsrefinedstorage     | 5.1.55                       | EnderIO-1.12.2-5.1.55.jar                                      | None                                     |
	| LCHIJA | enderiointegrationforestry        | 5.1.55                       | EnderIO-1.12.2-5.1.55.jar                                      | None                                     |
	| LCHIJA | enderiointegrationticlate         | 5.1.55                       | EnderIO-1.12.2-5.1.55.jar                                      | None                                     |
	| LCHIJA | enderiomachines                   | 5.1.55                       | EnderIO-1.12.2-5.1.55.jar                                      | None                                     |
	| LCHIJA | enderiopowertools                 | 5.1.55                       | EnderIO-1.12.2-5.1.55.jar                                      | None                                     |
	| LCHIJA | enderioendergy                    | 5.1.55                       | EnderIO-endergy-1.12.2-5.1.55.jar                              | None                                     |
	| LCHIJA | enderstorage                      | 2.4.6.137                    | EnderStorage-1.12.2-2.4.6.137-universal.jar                    | f1850c39b2516232a2108a7bd84d1cb5df93b261 |
	| LCHIJA | galacticraftcore                  | 4.0.2.244                    | GalacticraftCore-1.12.2-4.0.2.244.jar                          | None                                     |
	| LCHIJA | galacticraftplanets               | 4.0.2.244                    | Galacticraft-Planets-1.12.2-4.0.2.244.jar                      | None                                     |
	| LCHIJA | geneticsreborn                    | 1.20                         | geneticsreborn-1.12-1.21.jar                                   | None                                     |
	| LCHIJA | waila                             | 1.8.26                       | Hwyla-Mod-1.12.2.jar                                           | None                                     |
	| LCHIJA | inventorytweaks                   | 1.63+release.109.220f184     | InventoryTweaks-1.63.jar                                       | 55d2cd4f5f0961410bf7b91ef6c6bf00a766dcbe |
	| LCHIJA | ironchest                         | 1.12.2-7.0.67.844            | ironchest-1.12.2-7.0.72.847.jar                                | None                                     |
	| LCHIJA | llor                              | 1.1.6-mc1.12.2               | LLOverlayReloaded-1.1.6-mc1.12.2.jar                           | None                                     |
	| LCHIJA | mcjtylib_ng                       | 3.5.4                        | mcjtylib-1.12-3.5.4.jar                                        | None                                     |
	| LCHIJA | minihud                           | 0.13.1                       | minihud-1.12.2-0.13.1.jar                                      | 2b03e1423915a189b8094816baa18f239d576dff |
	| LCHIJA | orespawn                          | 3.3.1                        | MMD-OreSpawn-1.12.2.jar                                        | d476d1b22b218a10d845928d1665d45fce301b27 |
	| LCHIJA | naturescompass                    | 1.8.0                        | NaturesCompass-1.12.2-1.8.0.jar                                | None                                     |
	| LCHIJA | oredictdumper                     | 5.1.0                        | OreDictDumper-1.12-5.1.0.jar                                   | None                                     |
	| LCHIJA | pressure                          | 1.3.1.6                      | pressure-1.3.1.6-mc1.12.1.jar                                  | None                                     |
	| LCHIJA | rewired                           | 1.12.2                       | ReWIRED-1.0.7.jar                                              | None                                     |
	| LCHIJA | rftools                           | 7.73                         | rftools-1.12-7.73.jar                                          | None                                     |
	| LCHIJA | rftoolsdim                        | 5.71                         | rftoolsdim-1.12-5.71.jar                                       | None                                     |
	| LCHIJA | chunkbase_villageinfo_ssp         | 2.1                          | VillageInfoSSP-1.12.2-2.1.jar                                  | None                                     |
	| LCHIJA | worldedit                         | 6.1.10-SNAPSHOT              | worldedit-forge-mc1.12.2-6.1.10-SNAPSHOT-dist.jar              | None                                     |
	| LCHIJA | worldeditcuife2                   | 2.2.0-mf-1.12.2-14.23.5.2768 | WorldEdit+CUI+Forge+Edition+2-2.2.0-mf-1.12.2-14.23.5.2768.jar | None                                     |
	| LCHIJA | xaerominimap                      | 20.5.0                       | Xaeros_Minimap_20.5.0_Forge_1.12.jar                           | None                                     |
	| LCHIJA | xaeroworldmap                     | 1.5.5                        | XaerosWorldMap_1.5.5_Forge_1.12.jar                            | None                                     |

	Loaded coremods (and transformers): 
Inventory Tweaks Coremod (InventoryTweaks-1.63.jar)
  invtweaks.forge.asm.ContainerTransformer
TransformerLoader (OpenComputers-MC1.12.2-1.7.5.192.jar)
  li.cil.oc.common.asm.ClassTransformer
LoadingPlugin (Xaeros_Minimap_20.5.0_Forge_1.12.jar)
  xaero.common.core.transformer.ChunkTransformer
  xaero.common.core.transformer.NetHandlerPlayClientTransformer
MicdoodlePlugin (MicdoodleCore-1.12.2-4.0.2.244.jar)
  micdoodle8.mods.miccore.MicdoodleTransformer
BaseMetals (BaseMetals-1.12.2.jar)
  
EnderCorePlugin (EnderCore-1.12.2-0.5.73-core.jar)
  com.enderio.core.common.transform.EnderCoreTransformer
  com.enderio.core.common.transform.SimpleMixinPatcher
	GL info: ' Vendor: 'X.Org' Version: '4.5 (Compatibility Profile) Mesa 19.3.4' Renderer: 'AMD Radeon HD 7900 Series (TAHITI, DRM 3.36.0, 5.5.5-1-default, LLVM 9.0.1)'
	List of loaded APIs: 
		* cofhapi (2.5.0) from CoFHCore-1.12.2-4.6.3.27-universal.jar
		* enderioapi (4.0.0) from EnderIO-1.12.2-5.1.55.jar
		* enderioapi|addon (4.0.0) from EnderIO-1.12.2-5.1.55.jar
		* enderioapi|capacitor (4.0.0) from EnderIO-1.12.2-5.1.55.jar
		* enderioapi|conduits (4.0.0) from EnderIO-1.12.2-5.1.55.jar
		* enderioapi|farm (4.0.0) from EnderIO-1.12.2-5.1.55.jar
		* enderioapi|redstone (4.0.0) from EnderIO-1.12.2-5.1.55.jar
		* enderioapi|teleport (4.0.0) from EnderIO-1.12.2-5.1.55.jar
		* enderioapi|tools (4.0.0) from EnderIO-1.12.2-5.1.55.jar
		* enderioapi|upgrades (4.0.0) from EnderIO-1.12.2-5.1.55.jar
		* Galacticraft API (1.0) from GalacticraftCore-1.12.2-4.0.2.244.jar
		* JustEnoughItemsAPI (4.13.0) from jei_1.12.2-4.15.0.293.jar
		* opencomputersapi|component (7.0.0-alpha) from OpenComputers-MC1.12.2-1.7.5.192.jar
		* opencomputersapi|core (7.0.0-alpha) from OpenComputers-MC1.12.2-1.7.5.192.jar
		* opencomputersapi|driver (7.0.0-alpha) from OpenComputers-MC1.12.2-1.7.5.192.jar
		* opencomputersapi|driver|item (7.0.0-alpha) from OpenComputers-MC1.12.2-1.7.5.192.jar
		* opencomputersapi|event (7.0.0-alpha) from OpenComputers-MC1.12.2-1.7.5.192.jar
		* opencomputersapi|filesystem (7.0.0-alpha) from OpenComputers-MC1.12.2-1.7.5.192.jar
		* opencomputersapi|internal (7.0.0-alpha) from OpenComputers-MC1.12.2-1.7.5.192.jar
		* opencomputersapi|machine (7.0.0-alpha) from OpenComputers-MC1.12.2-1.7.5.192.jar
		* opencomputersapi|manual (7.0.0-alpha) from OpenComputers-MC1.12.2-1.7.5.192.jar
		* opencomputersapi|network (7.0.0-alpha) from OpenComputers-MC1.12.2-1.7.5.192.jar
		* opencomputersapi|prefab (7.0.0-alpha) from OpenComputers-MC1.12.2-1.7.5.192.jar
		* pressureAPI (1.3.1.6) from pressure-1.3.1.6-mc1.12.1.jar
		* redstonefluxapi (2.1.0) from RedstoneFlux-1.12-2.1.0.6-universal.jar
		* WailaAPI (1.3) from Hwyla-Mod-1.12.2.jar
	Ender IO: No known problems detected.
```

**Comment by 7eggert** [comment]
After upgrading, it's line 139.

**Comment by clubpetey** [comment]
I've stopped the NPE from occurring, but cannot determine the root cause.  Something in your world created a DNAhelix with a bad gene name.  

I've added some logging, so after you update, when you attempt to decrypt the helix, you should a log entry starting: ""Invalid forced-gene: "  If you can provide me the the full log message, I may be able to better track down what happened.

**Comment by 7eggert** [comment]
I tried several things, this happens each time I put a (not yet known) mutated basic DNA into the decryptor. (cell + sugar sugar into potion of mutation, extract, decrypt→crash)

(Waiting for curse to release the new jar.)

PS: When using the regular basic gene, I can create the plasmoids. I guess the mutated plasmoid / mutated basic gene is disabled because I'm not using hard mode.
