### ISSUE TITLE
Plasmid Infuser crashes the game when placing a Creeper DNA Helix and DNA Plasmid in it

### ISSUE THREAD

**Issue by ronyala** [TheUnderTaker11/GeneticsReborn#171]
If you try to place a DNA Plasmid of type 'gene not set' with a DNA Helix of type Creeper in the Plasmid Infuser, the game will crash.

**Mod version:** 1.25 (although the crash report says 1.20 for some reason), downloaded from curseforge
**Forge version:** 1.12.2-forge1.12.2-14.23.5.2847 (the 'latest' edition)

**Steps to reproduce the issue:**

1) Get an Organic Matter of type Creeper from a creeper using a scraper.
2) Place the Organic Matter in a Cell Analyser, outputs a Cell of type creeper.
3) Place the Cell in a DNA Extractor, get a DNA Helix of type creeper.
4) Take a DNA Plasmid(Gene not set) from the creative inventory.
5) Place the DNA Plasmid and DNA Helix in the Plasmid Infuser.

* Note: if it helps, the bug exists from at least version 1.23, when I started using the mod in the first place.

**Stack trace**

```
java.lang.NullPointerException
    at com.theundertaker11.geneticsreborn.api.capability.genes.EnumGenes.getNumberNeeded(EnumGenes.java:199)
    at com.theundertaker11.geneticsreborn.blocks.plasmidinfuser.GRTileEntityPlasmidInfuser.smeltItem(GRTileEntityPlasmidInfuser.java:100)
    at com.theundertaker11.geneticsreborn.blocks.plasmidinfuser.GRTileEntityPlasmidInfuser.canSmelt(GRTileEntityPlasmidInfuser.java:69)
    at com.theundertaker11.geneticsreborn.blocks.plasmidinfuser.GRTileEntityPlasmidInfuser.update(GRTileEntityPlasmidInfuser.java:50)
    at net.minecraft.world.World.redirect$zbe000$tileEntityUpdate(World.java:4137)
    at net.minecraft.world.World.updateEntities(World.java:1838)
    at net.minecraft.client.Minecraft.runTick(Minecraft.java:1847)
    at net.minecraft.client.Minecraft.runGameLoop(Minecraft.java:1098)
    at net.minecraft.client.Minecraft.run(Minecraft.java:3942)
    at net.minecraft.client.main.Main.main(SourceFile:123)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:498)
    at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
    at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
```

Edit: changed the full crash report for just the stack trace

**Comment by clubpetey** [comment]
Fixed in 1.26
