### ISSUE TITLE
Potion of Cell Growth crashes game

### ISSUE THREAD

**Issue by ronyala** [TheUnderTaker11/GeneticsReborn#183]
For some reason, if you splash a potion of Cell Growth on yourself (throwing it when looking up and it falls on top of you), the game crashes.

*Mod version:* 1.28, with no other mods installed
*Forge version:* 1.12.2-14.23.5.2847

#### Stack trace:
```
Description: Ticking entity

java.lang.NullPointerException: Ticking entity
	at com.theundertaker11.geneticsreborn.potions.GREntityPotion.applyGrowth(GREntityPotion.java:142)
	at com.theundertaker11.geneticsreborn.potions.GREntityPotion.applySplash(GREntityPotion.java:116)
	at com.theundertaker11.geneticsreborn.potions.GREntityPotion.func_70184_a(GREntityPotion.java:91)
	at net.minecraft.entity.projectile.EntityThrowable.func_70071_h_(EntityThrowable.java:249)
	at net.minecraft.world.World.func_72866_a(World.java:1996)
	at net.minecraft.world.WorldServer.func_72866_a(WorldServer.java:832)
	at net.minecraft.world.World.func_72870_g(World.java:1958)
	at net.minecraft.world.World.func_72939_s(World.java:1762)
	at net.minecraft.world.WorldServer.func_72939_s(WorldServer.java:613)
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:767)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:668)
	at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:185)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:526)
	at java.lang.Thread.run(Thread.java:748)


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Server thread
Stacktrace:
	at com.theundertaker11.geneticsreborn.potions.GREntityPotion.applyGrowth(GREntityPotion.java:142)
	at com.theundertaker11.geneticsreborn.potions.GREntityPotion.applySplash(GREntityPotion.java:116)
	at com.theundertaker11.geneticsreborn.potions.GREntityPotion.func_70184_a(GREntityPotion.java:91)
	at net.minecraft.entity.projectile.EntityThrowable.func_70071_h_(EntityThrowable.java:249)
	at net.minecraft.world.World.func_72866_a(World.java:1996)
	at net.minecraft.world.WorldServer.func_72866_a(WorldServer.java:832)
	at net.minecraft.world.World.func_72870_g(World.java:1958)

-- Entity being ticked --
Details:
	Entity Type: minecraft:viralpotion (com.theundertaker11.geneticsreborn.potions.GREntityPotion)
	Entity ID: 4482
	Entity Name: entity.viralpotion.name
	Entity's Exact location: 146.56, 78.13, 263.88
	Entity's Block location: World: (146,78,263), Chunk: (at 2,4,7 in 9,16; contains blocks 144,0,256 to 159,255,271), Region: (0,0; contains chunks 0,0 to 31,31, blocks 0,0,0 to 511,255,511)
	Entity's Momentum: 0.00, -0.46, -0.00
	Entity's Passengers: []
	Entity's Vehicle: ~~ERROR~~ NullPointerException: null
Stacktrace:
	at net.minecraft.world.World.func_72939_s(World.java:1762)
	at net.minecraft.world.WorldServer.func_72939_s(WorldServer.java:613)
```

* Also, apparently each potion of Genetics Reborn has 3-4 versions that appear when searching their names in creative, but only one version of each is shown in the 'Genetics Reborn' category. Not sure if these are related, but it's just a bit weird.

**Comment by clubpetey** [comment]
Fixed in 1.29
