### ISSUE TITLE
Game crash if hit by a Wither Skull with Thorns mutation

### ISSUE THREAD

**Issue by ronyala** [TheUnderTaker11/GeneticsReborn#188]
Mod version: 1.28

If you get hit by a Wither Skull when you have the Thorns mutation, the game will crash.
```
---- Minecraft Crash Report ----
// On the bright side, I bought you a teddy bear!

Time: 4/20/20 1:21 PM
Description: Ticking entity

java.lang.NullPointerException: Ticking entity
	at com.theundertaker11.geneticsreborn.event.OnEntityHurt.onHurt(OnEntityHurt.java:98)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_24_OnEntityHurt_onHurt_LivingHurtEvent.invoke(.dynamic)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90)
	at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:182)
	at net.minecraftforge.common.ForgeHooks.onLivingHurt(ForgeHooks.java:604)
	at net.minecraft.entity.player.EntityPlayer.func_70665_d(EntityPlayer.java:1120)
	at net.minecraft.entity.EntityLivingBase.func_70097_a(EntityLivingBase.java:926)
	at net.minecraft.entity.player.EntityPlayer.func_70097_a(EntityPlayer.java:1038)
	at net.minecraft.entity.player.EntityPlayerMP.func_70097_a(EntityPlayerMP.java:645)
	at net.minecraft.world.Explosion.func_77278_a(Explosion.java:159)
	at net.minecraft.world.WorldServer.func_72885_a(WorldServer.java:1169)
	at net.minecraft.entity.projectile.EntityWitherSkull.func_70227_a(EntityWitherSkull.java:118)
	at net.minecraft.entity.projectile.EntityFireball.func_70071_h_(EntityFireball.java:98)
	at net.minecraft.world.World.func_72866_a(World.java:1996)
	at net.minecraft.world.WorldServer.func_72866_a(WorldServer.java:832)
	at net.minecraft.world.World.func_72870_g(World.java:1958)
	at net.minecraft.world.World.func_72939_s(World.java:1762)
	at net.minecraft.world.WorldServer.func_72939_s(WorldServer.java:613)
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:767)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:668)
	at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:185)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:526)
	at java.lang.Thread.run(Thread.java:748)


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Server thread
Stacktrace:
	at com.theundertaker11.geneticsreborn.event.OnEntityHurt.onHurt(OnEntityHurt.java:98)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_24_OnEntityHurt_onHurt_LivingHurtEvent.invoke(.dynamic)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90)
	at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:182)
	at net.minecraftforge.common.ForgeHooks.onLivingHurt(ForgeHooks.java:604)
	at net.minecraft.entity.player.EntityPlayer.func_70665_d(EntityPlayer.java:1120)
	at net.minecraft.entity.EntityLivingBase.func_70097_a(EntityLivingBase.java:926)
	at net.minecraft.entity.player.EntityPlayer.func_70097_a(EntityPlayer.java:1038)
	at net.minecraft.entity.player.EntityPlayerMP.func_70097_a(EntityPlayerMP.java:645)
	at net.minecraft.world.Explosion.func_77278_a(Explosion.java:159)
	at net.minecraft.world.WorldServer.func_72885_a(WorldServer.java:1169)
	at net.minecraft.entity.projectile.EntityWitherSkull.func_70227_a(EntityWitherSkull.java:118)
	at net.minecraft.entity.projectile.EntityFireball.func_70071_h_(EntityFireball.java:98)
	at net.minecraft.world.World.func_72866_a(World.java:1996)
	at net.minecraft.world.WorldServer.func_72866_a(WorldServer.java:832)
	at net.minecraft.world.World.func_72870_g(World.java:1958)

-- Entity being ticked --
Details:
	Entity Type: minecraft:wither_skull (net.minecraft.entity.projectile.EntityWitherSkull)
	Entity ID: 1389
	Entity Name: entity.WitherSkull.name
	Entity's Exact location: 589.38, 91.14, 253.69
	Entity's Block location: World: (589,91,253), Chunk: (at 13,5,13 in 36,15; contains blocks 576,0,240 to 591,255,255), Region: (1,0; contains chunks 32,0 to 63,31, blocks 512,0,0 to 1023,255,511)
	Entity's Momentum: 0.05, -1.17, 0.17
	Entity's Passengers: []
	Entity's Vehicle: ~~ERROR~~ NullPointerException: null
Stacktrace:
	at net.minecraft.world.World.func_72939_s(World.java:1762)
	at net.minecraft.world.WorldServer.func_72939_s(WorldServer.java:613)
```
Edit: it seems that an almost identical crash is happening with other things too, such as TNT and falling sand

**Comment by clubpetey** [comment]
Fun Fact, Damage from a whither skull is not considered "damage by the wither" in the code.  Fixed in 1.29.
