### ISSUE TITLE
Game crashes when player with thorns walks into a cactus

### ISSUE THREAD

**Issue by ghost** [TheUnderTaker11/GeneticsReborn#208]
Mod version 1.29

---- Minecraft Crash Report ----
// Sorry :(

Time: 8/28/20 11:50 PM
Description: Colliding entity with block

java.lang.NullPointerException: Colliding entity with block
	at com.theundertaker11.geneticsreborn.event.OnEntityHurt.onHurt(OnEntityHurt.java:101)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_24_OnEntityHurt_onHurt_LivingHurtEvent.invoke(.dynamic)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90)
	at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:182)
	at net.minecraftforge.common.ForgeHooks.onLivingHurt(ForgeHooks.java:604)
	at net.minecraft.entity.player.EntityPlayer.func_70665_d(EntityPlayer.java:1120)
	at net.minecraft.entity.EntityLivingBase.func_70097_a(EntityLivingBase.java:926)
	at net.minecraft.entity.player.EntityPlayer.func_70097_a(EntityPlayer.java:1038)
	at net.minecraft.entity.player.EntityPlayerMP.func_70097_a(EntityPlayerMP.java:645)
	at net.minecraft.block.BlockCactus.func_180634_a(BlockCactus.java:126)
	at net.minecraft.entity.Entity.func_145775_I(Entity.java:1044)
	at net.minecraft.entity.Entity.func_70091_d(Entity.java:964)
	at net.minecraft.entity.EntityLivingBase.func_191986_a(EntityLivingBase.java:1958)
	at net.minecraft.entity.player.EntityPlayer.func_191986_a(EntityPlayer.java:1827)
	at net.minecraft.entity.EntityLivingBase.func_70636_d(EntityLivingBase.java:2393)
	at net.minecraft.entity.player.EntityPlayer.func_70636_d(EntityPlayer.java:513)
	at net.minecraft.entity.EntityLivingBase.func_70071_h_(EntityLivingBase.java:2179)
	at net.minecraft.entity.player.EntityPlayer.func_70071_h_(EntityPlayer.java:234)
	at net.minecraft.entity.player.EntityPlayerMP.func_71127_g(EntityPlayerMP.java:382)
	at net.minecraft.network.NetHandlerPlayServer.func_73660_a(NetHandlerPlayServer.java:173)
	at net.minecraftforge.fml.common.network.handshake.NetworkDispatcher$1.func_73660_a(NetworkDispatcher.java:209)
	at net.minecraft.network.NetworkManager.func_74428_b(NetworkManager.java:285)
	at net.minecraft.network.NetworkSystem.func_151269_c(NetworkSystem.java:180)
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:790)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:668)
	at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:185)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:526)
	at java.lang.Thread.run(Thread.java:745)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Server thread
Stacktrace:
	at com.theundertaker11.geneticsreborn.event.OnEntityHurt.onHurt(OnEntityHurt.java:101)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_24_OnEntityHurt_onHurt_LivingHurtEvent.invoke(.dynamic)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90)
	at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:182)
	at net.minecraftforge.common.ForgeHooks.onLivingHurt(ForgeHooks.java:604)
	at net.minecraft.entity.player.EntityPlayer.func_70665_d(EntityPlayer.java:1120)
	at net.minecraft.entity.EntityLivingBase.func_70097_a(EntityLivingBase.java:926)
	at net.minecraft.entity.player.EntityPlayer.func_70097_a(EntityPlayer.java:1038)
	at net.minecraft.entity.player.EntityPlayerMP.func_70097_a(EntityPlayerMP.java:645)
	at net.minecraft.block.BlockCactus.func_180634_a(BlockCactus.java:126)

-- Block being collided with --
Details:
	Block: minecraft:cactus[age=1]
	Block location: World: (-109,64,113), Chunk: (at 3,4,1 in -7,7; contains blocks -112,0,112 to -97,255,127), Region: (-1,0; contains chunks -32,0 to -1,31, blocks -512,0,0 to -1,255,511)
Stacktrace:
	at net.minecraft.entity.Entity.func_145775_I(Entity.java:1044)

-- Entity being checked for collision --
Details:
	Entity Type: null (net.minecraft.entity.player.EntityPlayerMP)
	Entity ID: 993
	Entity Name: Hafo0135
	Entity's Exact location: -108.56, 64.94, 113.40
	Entity's Block location: World: (-109,64,113), Chunk: (at 3,4,1 in -7,7; contains blocks -112,0,112 to -97,255,127), Region: (-1,0; contains chunks -32,0 to -1,31, blocks -512,0,0 to -1,255,511)
	Entity's Momentum: 0.00, 0.00, 0.00
	Entity's Passengers: []
	Entity's Vehicle: ~~ERROR~~ NullPointerException: null
Stacktrace:
	at net.minecraft.entity.Entity.func_70091_d(Entity.java:964)
	at net.minecraft.entity.EntityLivingBase.func_191986_a(EntityLivingBase.java:1958)
	at net.minecraft.entity.player.EntityPlayer.func_191986_a(EntityPlayer.java:1827)
	at net.minecraft.entity.EntityLivingBase.func_70636_d(EntityLivingBase.java:2393)
	at net.minecraft.entity.player.EntityPlayer.func_70636_d(EntityPlayer.java:513)
	at net.minecraft.entity.EntityLivingBase.func_70071_h_(EntityLivingBase.java:2179)
	at net.minecraft.entity.player.EntityPlayer.func_70071_h_(EntityPlayer.java:234)

-- Player being ticked --
Details:
	Entity Type: null (net.minecraft.entity.player.EntityPlayerMP)
	Entity ID: 993
	Entity Name: Hafo0135
	Entity's Exact location: -108.56, 64.94, 113.40
	Entity's Block location: World: (-109,64,113), Chunk: (at 3,4,1 in -7,7; contains blocks -112,0,112 to -97,255,127), Region: (-1,0; contains chunks -32,0 to -1,31, blocks -512,0,0 to -1,255,511)
	Entity's Momentum: 0.00, 0.00, 0.00
	Entity's Passengers: []
	Entity's Vehicle: ~~ERROR~~ NullPointerException: null
Stacktrace:
	at net.minecraft.entity.player.EntityPlayerMP.func_71127_g(EntityPlayerMP.java:382)
	at net.minecraft.network.NetHandlerPlayServer.func_73660_a(NetHandlerPlayServer.java:173)
	at net.minecraftforge.fml.common.network.handshake.NetworkDispatcher$1.func_73660_a(NetworkDispatcher.java:209)
	at net.minecraft.network.NetworkManager.func_74428_b(NetworkManager.java:285)

-- Ticking connection --
Details:
	Connection: net.minecraft.network.NetworkManager@7ab66c74
Stacktrace:
	at net.minecraft.network.NetworkSystem.func_151269_c(NetworkSystem.java:180)
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:790)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:668)
	at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:185)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:526)
	at java.lang.Thread.run(Thread.java:745)

-- System Details --
Details:
	Minecraft Version: 1.12.2
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_51, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 759891648 bytes (724 MB) / 1238368256 bytes (1181 MB) up to 2863661056 bytes (2731 MB)
	JVM Flags: 4 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx3072m -Xms256m -XX:PermSize=256m
	IntCache: cache: 0, tcache: 0, allocated: 13, tallocated: 95
	FML: MCP 9.42 Powered by Forge 14.23.5.2854 5 mods loaded, 5 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored

	| State  | ID             | Version      | Source                        | Signature                                |
	|:------ |:-------------- |:------------ |:----------------------------- |:---------------------------------------- |
	| LCHIJA | minecraft      | 1.12.2       | minecraft.jar                 | None                                     |
	| LCHIJA | mcp            | 9.42         | minecraft.jar                 | None                                     |
	| LCHIJA | FML            | 8.0.99.99    | forge-1.12.2-14.23.5.2854.jar | e3c3d50c7c986df74c645c0ac54639741c90a557 |
	| LCHIJA | forge          | 14.23.5.2854 | forge-1.12.2-14.23.5.2854.jar | e3c3d50c7c986df74c645c0ac54639741c90a557 |
	| LCHIJA | geneticsreborn | 1.28         | geneticsreborn-1.12-1.29.jar  | None                                     |

	Loaded coremods (and transformers): 
	GL info: ~~ERROR~~ RuntimeException: No OpenGL context found in the current thread.
	Profiler Position: N/A (disabled)
	Player Count: 1 / 8; [EntityPlayerMP['Hafo0135'/993, l='CactusThorn', x=-108.56, y=64.94, z=113.40]]
	Type: Integrated Server (map_client.txt)
	Is Modded: Definitely; Client brand changed to 'fml,forge'

**Comment by SonicX8000** [comment]
Game also crashes when standing on Magma Blocks, swimming in Lava, being on fire, taking wither or poison damage as well as throwing Ender Pearls if you have the THORNS gene. Might apply for any non-entity damage source. Being on fire will pretty much lock your world as it crashes the game when the fire damages you.

Ender Pearl crash:
https://pastebin.com/gXtgC7tq

Magma Block crash:
https://pastebin.com/VM3XwdFS

On another note, it also makes you immune to fall damage, but it doesn't crash the game.

**Comment by clubpetey** [comment]
Fixed in 1.30, released after PR merge.
