### ISSUE TITLE
warning message in server

### ISSUE THREAD

**Issue by Misoss** [TheUnderTaker11/GeneticsReborn#98]
Hi,
here is the server-side message that I can't solve.
Thank you for your help

`WARNING: More than one exception was raised. Will report only the first one and log others.
io.netty.handler.codec.EncoderException: java.lang.RuntimeException: Undefined discriminator for message type com.theundertaker11.geneticsreborn.packets.StepHeightChange in channel GeneticsReborn
        at io.netty.handler.codec.MessageToMessageEncoder.write(MessageToMessageEncoder.java:106)
        at io.netty.handler.codec.MessageToMessageCodec.write(MessageToMessageCodec.java:116)
        at io.netty.channel.AbstractChannelHandlerContext.invokeWrite0(AbstractChannelHandlerContext.java:738)
        at io.netty.channel.AbstractChannelHandlerContext.invokeWriteAndFlush(AbstractChannelHandlerContext.java:801)
        at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:814)
        at io.netty.channel.AbstractChannelHandlerContext.writeAndFlush(AbstractChannelHandlerContext.java:794)
        at io.netty.channel.AbstractChannelHandlerContext.writeAndFlush(AbstractChannelHandlerContext.java:831)
        at io.netty.channel.DefaultChannelPipeline.writeAndFlush(DefaultChannelPipeline.java:1032)
        at io.netty.channel.AbstractChannel.writeAndFlush(AbstractChannel.java:296)
        at net.minecraftforge.fml.common.network.simpleimpl.SimpleNetworkWrapper.sendTo(SimpleNetworkWrapper.java:250)
        at com.theundertaker11.geneticsreborn.event.PlayerTickEvent.checkStepAssist(PlayerTickEvent.java:138)
        at com.theundertaker11.geneticsreborn.event.PlayerTickEvent.onPlayerTick(PlayerTickEvent.java:115)
        at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_1884_PlayerTickEvent_onPlayerTick_PlayerTickEvent.invoke(.dynamic)
        at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90)
        at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:182)
        at net.minecraftforge.fml.common.FMLCommonHandler.onPlayerPreTick(FMLCommonHandler.java:365)
        at net.minecraft.entity.player.EntityPlayer.onUpdate(EntityPlayer.java:190)
        at net.minecraft.entity.player.EntityPlayerMP.onUpdateEntity(EntityPlayerMP.java:382)
        at net.minecraft.network.NetHandlerPlayServer.update(NetHandlerPlayServer.java:173)
        at net.minecraftforge.fml.common.network.handshake.NetworkDispatcher$1.update(NetworkDispatcher.java:209)
        at net.minecraft.network.NetworkManager.processReceivedPackets(NetworkManager.java:285)
        at net.minecraft.network.NetworkSystem.networkTick(NetworkSystem.java:180)
        at net.minecraft.server.MinecraftServer.updateTimeLightAndEntities(MinecraftServer.java:790)
        at net.minecraft.server.dedicated.DedicatedServer.updateTimeLightAndEntities(DedicatedServer.java:397)
        at net.minecraft.server.MinecraftServer.tick(MinecraftServer.java:668)
        at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:526)
        at java.lang.Thread.run(Thread.java:748)
Caused by: java.lang.RuntimeException: Undefined discriminator for message type com.theundertaker11.geneticsreborn.packets.StepHeightChange in channel GeneticsReborn
        at net.minecraftforge.fml.common.network.FMLIndexedMessageToMessageCodec.encode(FMLIndexedMessageToMessageCodec.java:76)
        at io.netty.handler.codec.MessageToMessageCodec$1.encode(MessageToMessageCodec.java:67)
        at io.netty.handler.codec.MessageToMessageEncoder.write(MessageToMessageEncoder.java:88)`

**Comment by clubpetey** [comment]
Thanks for the report.  We've already discovered this issue, referenced in Issue #96  and it has been fixed in the next release.  That release is due out the weekend of 11/2
